### PR TITLE
Fix Footer Format on Mobile

### PR DESCRIPTION
**Pull request by jakeacooley**
https://github.com/BanklessDAO/bankless-dao-ghost-website/issues/47

### CODE REVIEW

**Review by zberwaldt — APPROVED** [review]
Looks good to me.

@moshejs you might want to pull from develop to include these changes in what you're working on.

**Comment by moshejs** [comment]
Don't merge yet there are some bugs

**Comment by jakeacooley** [comment]
> Don't merge yet there are some bugs

In this PR?

**Comment by zberwaldt** [comment]
@moshejs I have your branch code locally at home. I'll go through and address any bugs.

**Review by zberwaldt — APPROVED** [review]
Good to merge. Thank you @jakeacooley

**Pull request merged**
